openapi: 3.0.0
info:
  title: T-shirts Store
  description: backend for handling t-shirts
  version: 0.0.1
  contact:
    email: taprearyan7@gmail.com
    url: "https://www.aryantapre.in"

# servers:
#   - url: http://localhost:4000/api/v1
#     description: for localhost - regular
#   - url: https://localhost:4000/api/v1
#     description: for localhost - secure

servers:
  - url: "{protocols}://localhost:{port}/api/{version}"
    description: for localhost - regular
    variables:
      protocols:
        default: http
        enum:
          - https
      port:
        default: 5000
        enum:
          - 4001
          - 4002
      version:
        default: v1
        enum:
          - v2
          - v3

  

components:
  securitySchemes:
    cookieAuth:
      type: apikey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer